name: Fetch Hourly Data

on:
  schedule:
    - cron: '0 * * * *'  # 1시간마다 실행

jobs:
  run-fetch-data:
    runs-on: ubuntu-latest

    steps:
      # 리포지토리 체크아웃
      - name: Check out repository
        uses: actions/checkout@v3
      
      # Python 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 필요 라이브러리 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 데이터 가져오는 스크립트 실행
      - name: Run fetch_data.py
        run: python hw8/fetch_data.py

      # 리포지토리의 최신 상태 가져오기 (충돌 방지)
      - name: Pull latest changes
        run: |
          git config --local user.email "guaum12@naver.com"
          git config --local user.name "sap2024"
          git pull origin main  # 브랜치 이름이 main이 맞는지 확인하세요.

      # 새로운 데이터를 리포지토리에 커밋
      - name: Commit and push data
        run: |
          git config --local user.email "guaum12@naver.com"
          git config --local user.name "sap2024"
          git add .
          git diff --cached --exit-code || git commit -m "Add hourly data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

         
