name: Fetch AWS Weather Data Hourly

on:
  schedule:
    - cron: '0 * * * *'  # 매 시간마다 실행

jobs:
  fetch-aws-data:
    runs-on: ubuntu-latest

    steps:
      # 리포지토리 체크아웃
      - name: Check out repository
        uses: actions/checkout@v3

      # Python 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 의존성 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      # 데이터 가져오기 스크립트 실행
      - name: Fetch AWS Data
        run: |
          python hw8/fetch_data.py
          echo "Data fetched at $(date)"

      # 최신 변경 사항 풀링
      - name: Pull latest changes
        run: |
          git config --local user.email "guaum12@naver.com"
          git config --local user.name "sap2024"
          git pull origin main --rebase

      # 파일 변경 사항 확인 및 디버깅용 로그 출력
      - name: Check for changes and debug
        run: |
          git status
          git diff

      # 새로운 데이터가 있을 경우 커밋 및 푸시
      - name: Commit and push data
        run: |
          git config --local user.email "guaum12@naver.com"
          git config --local user.name "sap2024"
          git add hw8/

          # 변경 사항이 있는지 확인 후 커밋 및 푸시
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add hourly AWS weather data"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


     

      
