name: Fetch AWS Weather Data Hourly

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  fetch-aws-data:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas sendgrid

      # Run the data fetch script
      - name: Fetch AWS Data
        run: |
          python hw8/fetch_data.py
          echo "Data fetched at $(date)"

      # Pull latest changes to avoid conflicts
      - name: Pull latest changes
        run: |
          git config --local user.email "guaum12@naver.com"
          git config --local user.name "sap2024"
          git pull origin main

      # Commit and push new data if there are changes
      - name: Commit and push data
        run: |
          git config --local user.email "guaum12@naver.com"
          git config --local user.name "sap2024"
          git add .
          # Check if there are any changes to commit
          if ! git diff --cached --quiet; then
            git commit -m "Add hourly AWS weather data"
            git push
          else
            echo "No changes to commit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



     

      
