name: Fetch Daily Data

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행

jobs:
  run-fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch_data.py
        run: python fetch_data.py
